name = "hr-portal-cloudflare-api"
main = "src/index.js"
compatibility_date = "2025-09-14"

[vars]
UPSTREAM_URL = 'https://script.google.com/macros/s/AKfycbz2pEc6aCqKnzXIdiPQZBH6lc6X9TUZewPmS2RfuuSTh9UKSERrakfcH13OrlsrCcH9Zw/exec'